# Generated by Django 3.0 on 2023-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
