# Generated by Django 4.2.5 on 2023-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0004_auto_20230905_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
